app = "ergofund-labs"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PUBLIC_ERGO_EXPLORER_URL = "https://api.ergoplatform.com"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "30s"
  method = "GET"
  path = "/api/health"
