services:
  - type: web
    name: bene-fundraising
    runtime: docker
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_ERGO_EXPLORER_URL
        value: https://api.ergoplatform.com
